### ISSUE TITLE
RuntimeError: Never call result.get() within a task!

### ISSUE THREAD

**Issue by korolevpavel** [korolevpavel/saleor-gateaway-sberbank#1]
При проверке статуса платежа через фоновое задание вылетает ошибка:
```
Traceback (most recent call last):
  File "/home/korolev/saleor/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/korolev/saleor/saleor/payment/gateways/sberbank/tasks.py", line 26, in check_status_sberbank_task
    self.retry(countdown=60)
  File "/home/korolev/saleor/lib/python3.6/site-packages/celery/app/task.py", line 715, in retry
    S.apply().get()
  File "/home/korolev/saleor/lib/python3.6/site-packages/celery/result.py", line 1015, in get
    assert_will_not_block()
  File "/home/korolev/saleor/lib/python3.6/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)

RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

**Comment by korolevpavel** [comment]
Предварительно, нужно запустить воркер:
```
celery -A saleor worker -l info
```
